### ISSUE TITLE
ReHack в DevTools выдаёт много ошибок 404

### ISSUE THREAD

**Issue by mystieneko** [TheAirBlow/HackPack#1]
Ни DevTools, ни плагин, ни расширение не работают. В DevTools видно много POST ошибок 404
![Screenshot_20221121-100907_Kiwi Browser](https://user-images.githubusercontent.com/65071577/202987605-46b0b5d8-9c0c-4733-b5a8-e2eb36f33606.png)

**Comment by TheAirBlow** [comment]
ReHack перестал работать потому что разрабы пофиксили дыру, которую плагин использовал.
Кароче, теперь получть ответы можно только после отправки ответов и только в тренировочных (даже в них иногда ответы не выдавало)

Кстати, ошибки 404 выше это сам РЭШ, не плагин.
