### ISSUE TITLE
будет ли поддержка новых b2t карточек Uchi.ru?

### ISSUE THREAD

**Issue by mystieneko** [TheAirBlow/HackPack#2]
сейчас нет поддержки таких карточек: https://uchi.ru/profile/students/player?task_id=2662&work_id=1829d0f8-350d-4376-b66b-7ac346b0198f&subject_id=1

то есть url другой для них

**Comment by TheAirBlow** [comment]
Может быть сделаю на новом веб-сайте :eyes:
